remove luminus and add multi-level download support

diff --git a/yans b/yans
--- a/yans
+++ b/yans
@@ -2,14 +2,12 @@
 
 usage() {
   name="${0##*/}"
-  echo "Provide either the credentials to Canvas or Luminus (or both)."
+  echo "Provide the credentials to Canvas."
   echo "By default, $name syncs to your default download location."
 
   echo "Usage:"
-  echo "  $name -v -k [CANVAS_API_KEY] -u [LUMINUS_USER_ID] -p [LUMINUS_PASSWORD] SYNC_DIR"
-  echo "Example:"
-  echo "  $name -u \"nusstu\\e0260000\" -p \"\$(pass show nus_password)\" ~/current"
-  exit "$1"
+  echo "  $name -v -k [API_KEY] SYNC_DIR"
+  exit 1
 }
 
 DEBUG() {
@@ -18,255 +16,113 @@ DEBUG() {
   fi
 }
 
+###############################################################################
+
 for arg in "$@"; do
   shift
   case "$arg" in
-    '--key')      set -- "$@" '-k'   ;;
-    '--user')     set -- "$@" '-u'   ;;
-    '--password') set -- "$@" '-p'   ;;
     '--help')     set -- "$@" '-h'   ;;
-    '--debug')    set -- "$@" '-D'   ;;
-    '--verbose')  set -- "$@" '-v'   ;;
+    '--debug')    set -- "$@" '-d'   ;;
+    '--clobber')  set -- "$@" '-c'   ;;
+    '--key')      set -- "$@" '-k'   ;;
     *)            set -- "$@" "$arg" ;;
   esac
 done
 
 key=
-user=
-password=
-verbose=false
+clobber=false
 debug=false
-while getopts "hvDdk:u:p:" o; do
+while getopts "hdck:u:p:" o; do
   case "$o" in
-    v) verbose=true ;;
-    D) debug=true ;;
+    d) debug=true ;;
+    c) clobber=true ;;
     k) key="$OPTARG";;
-    u) user="$OPTARG";;
-    p) password="$OPTARG";;
-    h | *) usage 0;;
+    h | *) usage;;
   esac
 done
 shift $((OPTIND-1))
 
-download_dir="${XDG_DOWNLOAD_DIR:-$HOME/Downloads}"
-if [ -n "$1" ]; then
-  ! [ -d "$1" ] && { echo "Please provide a valid sync directory."; exit 1; }
-  download_dir="$1"
-fi
-DEBUG "Download directory: $download_dir"
-
-if [ -z "$key" ] && { [ -z "$user" ] || [ -z "$password" ]; } then
- echo "Provide at least the credentials for Luminus or Canvas."
- exit 1
-fi
-
-if ! type rsync >/dev/null 2>&1; then 
-  echo "This program requires rsync."
+if [ -z "$key" ]; then
+  echo "Please provide Canvas API key."
   exit 1
 fi
 
+download_dir="${XDG_DOWNLOAD_DIR:-$HOME/Downloads}"
+if [ -n "$1" ]; then
+  download_dir="$1"
+fi
+mkdir -p "$download_dir"
+cd "$download_dir" || exit 1
+
 ###############################################################################
 
-LUMINUS_VAFS_URL="https://vafs.nus.edu.sg/adfs/oauth2/authorize?response_type=code&client_id=E10493A3B1024F14BDC7D0D8B9F649E9-234390&state=V6E9kYSq3DDQ72fSZZYFzLNKFT9dz38vpoR93IL8&redirect_uri=https://luminus.nus.edu.sg/auth/callback&scope=&resource=sg_edu_nus_oauth&nonce=V6E9kYSq3DDQ72fSZZYFzLNKFT9dz38vpoR93IL8"
-LUMINUS_DOMAIN="https://luminus.nus.edu.sg"
-LUMINUS_REDIRECT_API="/auth/callback"
-LUMINUS_JWT_API="/v2/api/login/adfstoken"
-LUMINUS_MODULE_API="/v2/api/module/?populate=Creator,termDetail,isMandatory"
-LUMINUS_FILES_API="/v2/api/files/?populate=totalFileCount,subFolderCount,TotalSize"
-
 CANVAS_DOMAIN="https://canvas.nus.edu.sg"
-CANVAS_AUTH_API="/api/v1/users/self"
-CANVAS_MODULES_API="/api/v1/courses"
-CANVAS_FILES_SUFFIX="files?per_page=30"
+AUTH_API="/api/v1/users/self"
+COURSES_API="/api/v1/courses"
+FOLDERS_API="/api/v1/folders"
 
-# CANVAS_FOLDERS_API="/api/v1/folders"
-# CANVAS_FILES_API="/api/v1/files"
-# CANVAS_FOLDERS_SUFFIX="folders?per_page=30"
+###############################################################################
 
-TMP_DIR=$(mktemp -d)
-COOKIE_JAR=$(mktemp)
-clean() {
- rm -r "$TMP_DIR"
- rm "$COOKIE_JAR"
- exit "$1"
-}
-
-curl_common() {
+_curl() {
   curl -s \
+    -H "Authorization: Bearer $key" \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" \
     "$@"
 }
 
-wget_common() {
-  wget -q --show-progress "$@"
+_wget() {
+  if [ "$clobber" = true ]; then
+    wget -q --show-progress "$@"
+  else
+    wget -q -nc --show-progress "$@"
+  fi
 }
 
-auth_canvas() {
-  # $1 - API key
-  [ -n "$1" ] || clean 1
-
-  curl_common \
-    -H "Authorization: Bearer $1" \
-    "$CANVAS_DOMAIN$CANVAS_AUTH_API" >/dev/null
+authenticate() {
+  printf "Verifying Canvas API key... "
+  data=$(_curl "$CANVAS_DOMAIN$AUTH_API")
+  if [ "$(echo "$data" | jq -r 'has("errors")')" = true ]; then
+    printf "\nAuthentication failed. ";
+    echo "$data" | jq -r '.errors[0].message'
+    exit 1;
+  fi
+  echo "Success!"
 }
 
-auth_luminus() {
-  # $1 - username
-  # $2 - password
-  [ -n "$1" ] || clean 1
-  [ -n "$2" ] || clean 1
+sync_canvas_files() {
+  printf "Syncing Canvas files...\n"
 
-  curl_common -X POST \
-    --data-urlencode "UserName=$1" \
-    --data-urlencode "Password=$2" \
-    --data-urlencode "AuthMethod=FormsAuthentication" \
-    --cookie-jar "$COOKIE_JAR" \
-    "$LUMINUS_VAFS_URL"
-
-  redirect=$(curl_common -i -X POST \
-    --data-urlencode "UserName=$1" \
-    --data-urlencode "Password=$2" \
-    --data-urlencode "AuthMethod=FormsAuthentication" \
-    --cookie "$COOKIE_JAR" \
-    "$LUMINUS_VAFS_URL" | grep Location:)
-
-  redirect=${redirect#*code=}
-  code=${redirect%&state=*}
-
-  curl_common \
-    --data-urlencode "redirect_uri=$LUMINUS_DOMAIN$LUMINUS_REDIRECT_API" \
-    --data-urlencode "code=$code" \
-    --data-urlencode "resource=sg_edu_nus_oauth" \
-    --data-urlencode "client_id=E10493A3B1024F14BDC7D0D8B9F649E9-234390" \
-    --data-urlencode "grant_type=authorization_code" \
-    "$LUMINUS_DOMAIN$LUMINUS_JWT_API" | jq -r '.access_token'
-}
-
-luminus_sync() {
-  # $1 - jwt
-  jwt=$1
-  curl_common -H "Authorization: Bearer $jwt" "$LUMINUS_DOMAIN$LUMINUS_MODULE_API" |\
-    jq -r '.data[] | select(.term == "2210" and .id != "00000000-0000-0000-0000-000000000000") | .id, .name' |\
-  while read -r module_id; do
-    read -r module_name
-
-    # Remove potential '/' characters from module_name.
-    module_name="${module_name%%/*}"
-
-    if [ -z "$module_id" ] || [ -z "$module_name" ]; then
-      DEBUG "unexpected empty id or name"
-      continue
-    fi
-
-    echo "Syncing $module_name."
-
-    module_dir="$TMP_DIR/$module_name"
-    DEBUG "Creating module: $module_dir"
-    mkdir -p "$module_dir"
-
-    curl_common -H "Authorization: Bearer $jwt" "$LUMINUS_DOMAIN$LUMINUS_FILES_API&ParentId=$module_id" |\
-      jq -r '.data[] | select(.totalFileCount > 0) | .id, .name' |\
-    while read -r id; do
-      read -r name
-
-      if [ -z "$id" ] || [ -z "$name" ]; then
-        DEBUG "unexpected empty name or id: ${id:-null}"
-        break
-      fi
-
-      url=$(curl_common -H "Authorization: Bearer $jwt" "$LUMINUS_DOMAIN${LUMINUS_FILES_API%/*}/$id/downloadurl" |\
-      jq -r 'select(.code == 200).data')
-
-      if [ -z "$url" ]; then
-        echo "Failed retrieving module $module_name."
-        continue
-      fi
-
-      DEBUG "Get url: $url"
-
-      wget_common -P "$TMP_DIR" "$url"
-      f="$TMP_DIR/$(basename "$url")"
-
-      if [ "$(file --dereference --brief --mime-type -- "$f")" = "application/zip" ]; then
-        unzip -q -d "$module_dir" "$f"
-      else
-        mv "$f" "$module_dir/$name"
-      fi
-    done
-
-    if [ "$verbose" = true ]; then  
-      rsync -av "$module_dir" "$download_dir"
-    else
-      rsync -aq "$module_dir" "$download_dir" >/dev/null 2>&1
-    fi
-  done
-}
-
-canvas_get_files() {
-  # $1 - $key
-  curl_common -H "Authorization: Bearer $key" "$CANVAS_DOMAIN$CANVAS_MODULES_API" |\
-    jq -r '.[] | select(.course_code != null) | .id, .course_code' |\
-  while read -r course_id; do
+  _curl "$CANVAS_DOMAIN$COURSES_API" |\
+    jq -r '.[] | select(.course_code != null) | .name, .id, .course_code' |\
+  while read -r course_name; do
+    echo "$course_name"
+    read -r course_id
     read -r course_code
-
-    # Remove potential '/' characters from course_code.
     course_code="${course_code%%/*}"
+    mkdir -p "$course_code"
 
-    if [ -z "$course_id" ] || [ -z "$course_code" ]; then
-      DEBUG "unexpected empty id or code"
-      continue
-    fi
-
-    echo "Syncing $course_code."
-
-    course_dir="$TMP_DIR/$course_code"
-    DEBUG "Creating course: $course_dir"
-    mkdir -p "$course_dir"
-
-    # Support top-level files downloading for now.
-    curl_common -H "Authorization: Bearer $key" "$CANVAS_DOMAIN$CANVAS_MODULES_API/$course_id/$CANVAS_FILES_SUFFIX" |\
-      jq -r '.[] | select(.locked == false) | .url, .display_name' |\
+    _curl "$CANVAS_DOMAIN$COURSES_API/$course_id/files" |\
+      jq -r 'arrays | .[] | select(.locked == false) | .url, .folder_id, .display_name' |\
     while read -r url; do
-      read -r filename
+      read -r folder_id
+      read -r file_name
 
-      [ -n "$url" ] && [ -n "$filename" ] && wget_common -O "$course_dir/$filename" "$url"
+      folder_name="$(eval echo '$'__yans_folder_"$folder_id")"
+      if [ -z "$folder_name" ]; then
+        folder_name="$(_curl "$CANVAS_DOMAIN$FOLDERS_API/$folder_id" | jq -r '.full_name')"
+        folder_name="${folder_name#course files/}"
+        eval "__yans_folder_$folder_id='$folder_name'"
+      fi
+
+      mkdir -p "$course_code/$folder_name"
+      _wget -O "$course_code/$folder_name/$file_name" "$url"
     done
-
-    if [ "$verbose" = true ]; then  
-      rsync -av "$course_dir" "$download_dir"
-    else
-      rsync -aq "$course_dir" "$download_dir" >/dev/null 2>&1
-    fi
   done
 }
 
 main() {
-  # Luminus.
-  if [ -n "$user" ] && [ -n "$password" ]; then
-    echo "Logging into Luminus."
-    jwt=$(auth_luminus "$user" "$password")
-
-    if [ -z "$jwt" ]; then
-      echo "Failed to log into Luminus."
-      clean 1
-    fi
-
-    DEBUG "Got Luminus token: $jwt"
-
-    echo "Syncing Luminus files."
-    luminus_sync "$jwt"
-  fi
-
-  # Canvas.
-  if [ -z "$key" ]; then
-    clean 0
-  fi
-
-  echo "Verifying Canvas API key."
-  auth_canvas "$key" || { echo "Invalid Canvas API key."; clean 2; }
-  echo "Syncing Canvas files."
-  canvas_get_files "$key"
-  clean 0
+  authenticate && sync_canvas_files
 }
+
 main
